apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "token.kubevirt.io:generate"
rules:
- apiGroups:
  - "token.kubevirt.io"
  resources:
  - "virtualmachines/vnc"
  verbs:
  - "get"
